spring:
  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.xdu.irent.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true