spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rent?useSSL=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;&serverTimezone=UTC
    username: root
    password: root

logging:
  level:
    root: warn
    com.xdu: info
  file:
    name: log/blog-pro.log

